# Generated by Django 3.2.2 on 2021-05-07 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_text', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='create date')),
            ],
        ),
        migrations.CreateModel(
            name='ThoughtCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thought_category_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thought_text', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thoughtlogger.activity')),
                ('thought_categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thoughtlogger.thoughtcategory')),
            ],
        ),
    ]
