# Generated by Django 3.2.2 on 2021-05-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtlogger', '0002_thought_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thought',
            name='thought_categories',
        ),
        migrations.AddField(
            model_name='thought',
            name='thought_categories',
            field=models.ManyToManyField(to='thoughtlogger.ThoughtCategory'),
        ),
    ]
