# Generated by Django 3.2.2 on 2021-05-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtlogger', '0003_auto_20210507_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Errands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errand_text', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('next_attempt_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Routines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_text', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('days', models.ManyToManyField(to='thoughtlogger.Days')),
            ],
        ),
    ]
