# Generated by Django 3.2.2 on 2021-05-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtlogger', '0004_days_errands_routines'),
    ]

    operations = [
        migrations.AddField(
            model_name='errands',
            name='complete_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='errands',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='errands',
            name='next_attempt_date',
            field=models.DateTimeField(null=True),
        ),
    ]
