# Generated by Django 3.2.2 on 2021-05-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtlogger', '0005_auto_20210508_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routines',
            name='days',
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
